[tool.poetry]
name = "csv2xlsx"
version = "0.1.0"
description = "Converts to Excel XLSX from a TSV or CSV text file."
authors = ["Fredrik Mellström <fredrikm@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
openpyxl = "^3.0.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pylint = "^2.5.3"

[tool.poetry.scripts]
csv2xlsx = 'csv2xlsx.cli:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
